apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: iamwebwiz/udagram-api-feed:v2
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: udagram-env-configmap
                key: URL
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: udagram-env-configmap
                key: AWS_BUCKET
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: udagram-env-configmap
                key: AWS_PROFILE
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: udagram-env-configmap
                key: AWS_REGION
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: udagram-env-configmap
                key: JWT_SECRET
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: udagram-env-configmap
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: udagram-env-configmap
                key: POSTGRES_HOST
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: udagram-database-credentials
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: udagram-database-credentials
                key: POSTGRES_USERNAME
        volumeMounts:
          - name: udagram-aws-credentials
            mountPath: "/root/.aws/"
            readOnly: true
      volumes:
        - name: udagram-aws-credentials
          configMap:
            name: udagram-aws-credentials